### ISSUE TITLE
Recipe 'openwebrtc' failed at the build step 'configure'

### ISSUE THREAD

**Issue by phetroy** [nirbheek/cerbero#2]
Hi there,

Still going through the steps in this documentation:
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero

I just tried a clean build and running this command, I get the recipe 'openwebrtc' failed message:
./cerbero-uninstalled -c config/cross-android-armv7.cbc package openwebrtc

Do you know if there's any additional steps I may have to do?

Thanks!

**Recipe 'openwebrtc' failed at the build step 'configure'**
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "/Users/phetroy/Workspaces/cerbero/recipes/openwebrtc.recipe", line 130, in configure
    os.chdir(gir_file_path)
OSError: [Errno 2] No such file or directory: '/Users/phetroy/cerbero/dist/android_armv7/../darwin_x86_64/share/gir-1.0'

**Comment by phetroy** [comment]
Started a fresh build, and seems that this is not happening...
