### ISSUE TITLE
Build error on mac OS X Yosemite 10.10.1 with xcode version 6.0 (6A267n) installed

### ISSUE THREAD

**Issue by KerwinMa** [nirbheek/cerbero#25]
[(30/33) libusrsctp -> fetch ]
-----> Step done
[(30/33) libusrsctp -> extract ]
-----> Step done
[(30/33) libusrsctp -> configure ]
Recipe 'libusrsctp' failed at the build step 'configure'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "./cerbero/build/recipe.py", line 266, in <lambda>
    setattr(cls, step, lambda self, name=step: step_func(self, name))
  File "./cerbero/build/recipe.py", line 411, in _do_step
    stepfunc()
  File "/Users/kerwin.ma/cerbero/recipes/libusrsctp.recipe", line 42, in configure
    os.path.join(usrsctplib_path, "platform/net"))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: '/Applications/Xcode.app//Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/net'

**Comment by KerwinMa** [comment]
fixed the issue by making a shortcut of the sdk:
ln -s iPhoneSimulator8.0.sdk iPhoneSimulator.sdk

**Comment by nirbheek** [comment]
All development has moved to https://github.com/EricssonResearch/cerbero
